### ISSUE TITLE
ロゴのソースが欲しい

### ISSUE THREAD

**Issue by kou** [oss-gate/resources#1]
@sezemiadmin RabbitのテーマやWebサイトのfaviconを作るときなどにロゴを使いたいのですが、ロゴのソースをCreateive Commonsとか改変可能なライセンスで提供してもらえないでしょうか？

**Comment by sezemiadmin** [comment]
これでよいでしょうか。。(全然分かってません。。。。)
https://github.com/sezemiadmin/oss_gate_logo

**Comment by kou** [comment]
ありがとうございます！
そのPNGファイルの元になったファイルがあると思うんですが、それが欲しいのです。
ロゴってなんていうツールで作成したのでしょうか！？

**Comment by sezemiadmin** [comment]
スイマセン、、元ネタとなった素材はなく、https://pixlr.com/editor/ で一から作りました。。途中生成されるファイルはないため、faviconを作るようであれば、PNGのファイルを読み込んだ上で、↑のようなソフトでリサイズ等して頂くほかないです。。

**Comment by kou** [comment]
なるほど！わかりました！
どうするか考えておきます。

**Comment by kou** [comment]
@knokmki612 がSVGにしてくれたのでそれを https://github.com/oss-gate/resources/blob/master/image/icon.svg に入れました。
